name: PR checks
on: pull_request
jobs:
  job:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: google/osv/actions/analyze@action
      with:
        analyze-git: false
        pr-base: origin/${{ github.base_ref }}
        skip-pattern: '.github/workflows/.*'
    - run: |
        git diff --exit-code
